# input ProductOptions {
#   skip: Int = 0
#   take: Int = 24
#   sort: SortInput
# }

# input SortInput {
#   id: String = ASC
#   createdAt: String = null
#   updatedAt: String = null
#   name: String = null
#   slug: String = null
#   description: String = null
# }

query GetProducts($skip: Int = 0, $take: Int = 24) {
  products(options: { skip: $skip, take: $take, filter: null }) {
    totalItems
    items {
      id
      createdAt
      updatedAt
      languageCode
      name
      slug
      description
      enabled
      customFields
      variants {
        id
        productId
        sku
        name
        price
        currencyCode
        priceWithTax
        stockLevel
      }
      featuredAsset {
        id
        name
        type
        width
        height
        preview
        mimeType
      }
    }
  }
}
