query getProduct($slug: String! = "laptop") {
    product(slug: $slug) {
        id
        name
        slug
        description
        enabled
        languageCode
        createdAt
        updatedAt
        featuredAsset {
            id
            createdAt
            updatedAt
            name
            type
            fileSize
            mimeType
            width
            height
            source
            preview
        }
        assets {
            id
            createdAt
            updatedAt
            name
            type
            fileSize
            mimeType
            width
            height
            source
            preview
        }
        variants {
            id
            productId
            createdAt
            updatedAt
            languageCode
            sku
            name
            price
            currencyCode
            priceWithTax
            stockLevel
        }
        collections {
            id
            createdAt
            updatedAt
            languageCode
            name
            slug
            position
            description
            parentId
        }
    }
}
